---

- name: install apache
  package: >
    name={{ item }}
    state=installed

  with_items: "{{ httpd_packages }}"

- name: ensure apache is running
  service: >
    name={{ httpd_service }}
    state=started
    enabled=yes
