---

- name: configure logrotate partial
  template: >
    src=templates/httpd.logrotate.conf.j2
    dest=/etc/logrotate.d/httpd.logrotate.conf
    owner=root
    group=root
    mode=0644

  notify: ['reload logrotate']
