---

- name: include setup tasks
  include: setup.yml

- name: include installation tasks
  include: install.yml

- name: include logrotate partial configuration tasks
  include: logrotate.yml
  tags: ['logrotate']
