---

- name: ensure sites directory exists
  file: >
    path={{ httpd_sites_dir }}
    owner={{ httpd_user | default("apache") }}
    group={{ httpd_group | default("apache") }}
    mode=0755
    state=directory

  when: httpd_sites_dir is defined

- name: configure apache virtual hosts
  template: >
    src=templates/vhost.conf.j2
    dest={{ httpd_config_dir }}/{{ item.server_name }}.conf
    owner=root
    group=root
    mode=0644

  with_items: "{{ httpd_virtual_hosts }}"
  notify: ["restart apache"]
